/home/planck/anaconda3/envs/37/lib/python3.7/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
INFO: Training on 3119616 frames
INFO: Testing on 543360 frames
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    model['IGANet'] = IGANet(args).cuda()
  File "/DATA1/bikash_dutta/DL/Project/IGANet/model/model_IGANet.py", line 212, in __init__
    self.A = nn.Parameter(torch.tensor(self.graph.A, dtype=torch.float32), requires_grad=False).cuda(0)
KeyboardInterrupt
